# Copyright Bram Dufour. All Rights Reserved.
# Autor: Bram Dufour, bram.dufour8@gmail.com
# Date: 23-08-2020
# SPDX-License-Identifier: Apache-2.0
#
version: "2"

networks:
  basic:
services:
  # org4
  root.ca.org4.acme.com:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: root.ca.org4.acme.com
    ports:
      - "10054:7054"
    volumes:
      - ./fabric-ca/org4.acme.com/root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - basic
  tls.root.ca.org4.acme.com:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: tls.root.ca.org4.acme.com
    ports:
      - "10055:7054"
    volumes:
      - ./fabric-ca/org4.acme.com/tls-root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - basic
